= Trento App Role

Installs and configures Trento application, consisting of Web and
Wanda.

== Requirements

On the target:
* `zypper` package manager

== Role Variables

We keep all our variables documentation in the main README of the collection.

Advanced options protected by being vars:

[width="100%",cols="16%,57%,27%",options="header",]
|===
| app_enable_api_key | Enable API key usage. Mostly for testing
  purposes | true
|===

== Dependencies

This role is dependent on `suse.trento.trento` meta-role.

== Example Playbook

Some of the default values in this role come from the `trento`
meta-role. You can configure them in your inventory instead of
overriding the variables in this role.

[source, yaml]
----
- hosts: servers
  roles:
    - role: suse.trento.web
      app_server_name: "example.com"
      app_web_admin_password: "examplepass"
      app_web_postgres_password: "examplepass"
      app_wanda_postgres_password: "examplepass"
      app_rabbitmq_password: "examplepass"
----

== License

Apache License, Version 2.0

== Author Information

Developed and maintained by trento-developers@suse.com
Code repository is hosted on https://github.com/trento-project/ansible
