---
- name: Provision Trento agents
  hosts: agents
  roles:
    - role: agent
      become: true
      vars:
        agent_rabbitmq_host_group: "{{ 'rabbitmq_hosts' if (provision_rabbitmq | bool) else ''}}"
