# code: language=ansible
---
- name: Check firewalld package on prometheus and trento_server hosts
  hosts: prometheus_hosts:trento_server
  tasks:
    - name: Collect package facts
      ansible.builtin.package_facts:
        manager: auto
    - name: Check if a specific package is installed
      ansible.builtin.set_fact:
        firewalld_installed: "{{ 'firewalld' in ansible_facts.packages }}"
    - name: Check the status of firewalld
      ansible.builtin.systemd:
        name: firewalld.service
      register: firewalld_status

- name: Clean up trento components
  hosts: trento_server
  become: true
  tasks:
    - name: Trento services
      ansible.builtin.include_role:
        name: app
        tasks_from: cleanup
    - name: Proxy
      ansible.builtin.include_role:
        name: proxy
        tasks_from: cleanup

- name: Clean up postgres
  hosts: postgres_hosts
  become: true
  tasks:
    - name: Postgres
      ansible.builtin.include_role:
        name: postgres
        tasks_from: cleanup

- name: Clean up rabbitmq
  hosts: rabbitmq_hosts
  become: true
  tasks:
    - name: Rabbitmq
      ansible.builtin.include_role:
        name: rabbitmq
        tasks_from: cleanup

- name: Prometheus cleanup
  hosts: prometheus_hosts
  become: true
  tasks:
    - name: Prometheus
      ansible.builtin.include_role:
        name: prometheus
        tasks_from: cleanup
