---
- name: Provision Trento server components
  ansible.builtin.import_playbook: server.yml

- name: Provision Trento agents
  ansible.builtin.import_playbook: agent.yml
  vars:
    agent_web_api_key: "{{ hostvars[groups['trento_server'][0]].web_agents_api_key }}"
