# SPDX-FileCopyrightText: SUSE LLC
# SPDX-License-Identifier: Apache-2.0

---
- name: Restart FirewallD if previously running
  ansible.builtin.service:
    name: firewalld
    state: restarted
  when: __firewall_firewalld_status.status.ActiveState == "active"
