# code: language=ansible
---
- name: Remove nginx vhost file
  ansible.builtin.file:
    path: "{{ nginx_conf_base_dir }}/{{ nginx_vhost_dir }}/{{ nginx_vhost_filename }}.conf"
    state: absent
  notify:
    - Restart nginx

- name: Close http and https ports using firewalld
  ansible.builtin.command: >
    firewall-cmd --permanent --remove-port={{ item }}/tcp
  loop:
    - "{{ nginx_vhost_http_listen_port }}"
    - "{{ nginx_vhost_https_listen_port }}"
  when: firewalld_installed
  register: firewalld_close_nginx_ports
  changed_when: firewalld_close_nginx_ports.rc == 0
  notify:
    - Restart firewalld if running
