# SPDX-FileCopyrightText: SUSE LLC
# SPDX-License-Identifier: Apache-2.0

# code: language=ansible
---
- name: Determine SUSE modules to register
  ansible.builtin.set_fact:
    rabbitmq_suseconnect_subscriptions: >-
      {{
        []
        if (ansible_facts['distribution_major_version'] | int >= 16)
        else
        (
          [
            {'name': 'sle-module-basesystem', 'state': 'enabled'},
            {'name': 'sle-module-python3', 'state': 'enabled'}
          ]
          + ([{'name': 'sle-module-legacy', 'state': 'enabled'}] if ansible_facts['distribution_version'] == '15.6' else [])
        )
      }}
  when: enable_autoregister | bool

- name: Register with SCC and activate modules
  ansible.builtin.include_role:
    name: suseconnect
  vars:
    suseconnect_subscriptions: "{{ rabbitmq_suseconnect_subscriptions }}"
  when:
    - enable_autoregister | bool
    - rabbitmq_suseconnect_subscriptions | default([]) | length > 0

- name: Install RabbitMQ
  community.general.zypper:
    name: rabbitmq-server
    state: present
    update_cache: true

- name: Start RabbitMQ service
  ansible.builtin.service:
    name: rabbitmq-server
    state: started
    enabled: true

- name: Create RabbitMQ Trento vhost
  community.rabbitmq.rabbitmq_vhost:
    name: "{{ rabbitmq_vhost }}"
    node: "{{ rabbitmq_node_name }}"
    state: present

- name: Configure rabbitmq trento user
  community.rabbitmq.rabbitmq_user:
    user: "{{ rabbitmq_username }}"
    node: "{{ rabbitmq_node_name }}"
    password: "{{ rabbitmq_password }}"
    permissions:
      - vhost: "{{ rabbitmq_vhost }}"
        configure_priv: ".*"
        read_priv: ".*"
        write_priv: ".*"
