# code: language=ansible
---
- name: Include Docker installation variables
  ansible.builtin.include_vars: "../defaults/docker.yml"

- name: Stop wanda container
  community.docker.docker_container:
    name: "{{ wanda_container_name }}"
    state: absent
    keep_volumes: false

- name: Stop web container
  community.docker.docker_container:
    name: "{{ web_container_name }}"
    state: absent
    keep_volumes: false

- name: Stop checks container
  community.docker.docker_container:
    name: "{{ checks_container_name }}"
    state: absent
    keep_volumes: false

- name: Remove wanda container image
  when: remove_wanda_container_image == 'true'
  community.docker.docker_image:
    state: absent
    name: "{{ wanda_container_image }}"

- name: Remove checks container image
  when: remove_checks_container_image == 'true'
  community.docker.docker_image:
    state: absent
    name: "{{ checks_container_image }}"

- name: Remove web container image
  when: remove_web_container_image == 'true'
  community.docker.docker_image:
    state: absent
    name: "{{ web_container_image }}"

- name: Remove trento docker network
  community.docker.docker_network:
    name: "{{ docker_network_name }}"
    state: absent
    force: true
