---
namespace: "suse"
name: "trento"
version: "1.0.0"
readme: "README.adoc"

authors:
- "Kristiyan Kanchev <kristiyan.kanchev@suse.com>"

dependencies:
  ansible.posix: ">=1.6.2"
  community.general: ">=10.4.0"
  community.postgresql: ">=3.10.2"
  community.rabbitmq: ">=1.4.0"
  community.docker: ">=4.4.0"

license:
- Apache-2.0

tags:
- SUSE
- Trento
- SAP
- Deployment

repository: "https://github.com/trento-project/ansible"

manifest:
  directives:
  - graft playbooks
  - graft roles
  - graft docs
  - graft examples
  - include galaxy.yml README.adoc
  omit_default_directives: true
