= Trento Ansible Collection

Collection of Ansible playbooks and roles for Trento Project.

== Usage

After installation of the collection, you have to use FQCN to denote
the relevant component. All components of this collection are
namespaced with `suse.trento` prefix.

To run any of the bundled playbooks, for example, use the
following command:

[source,bash]
----
$ ansible-playbook -i <path-to-inventory> suse.trento.site
----

Please note the omission of file extension.

== Contents

The collections comprises of:

Playbooks::

server::: Install Trento server components
agent::: Install Trento agents
`site::: Compound playbook that executes both `server` and `agent`
  playbooks
cleanup::: Clean-up playbook that uninstalls all Trento components

Roles::

app::: Installs Trento Server components. Used in Deploymnet Playbook.
agent::: Installs Trento agent for information gathering. Used in Deployment Playbook.
postgres::: Installs PostgreSQL database server and configure it
with. Used in Deploymnet Playbook.  needed databases, users and
permissions. Used in Deploymnet Playbook.
rabbitmq::: Installs RabbitMQ message broker. Used in Deploymnet
Playbook.
prometheus::: Installs Prometheus metrics server. Used in Deploymnet
Playbook.
proxy::: Installs HTTP reverse proxy and configures it for
Trento-specific use-cases. Used in Deploymnet Playbook.

Detailed documentation for the comprising playbooks and roles could be
found xref:docs/README-trento.adoc[here].
