= Trento Ansible Collection

Collection of Ansible playbooks and roles for Trento Project.

== Usage

After installation of the collection, you have to use FQCN to denote
the relevant component. All components of this collection are
namespaced with `suse.trento` prefix.

To run the bundled `deploy.yml` playbook, for example, use the
following command:

[source,bash]
----
$ ansible-playbook -i <path-to-inventory> suse.trento.deploy
----

Please note the omission of file extension.

== Contents

The collections comprises of:

Playbooks::

Deployment Playbook::: Playbook for deploying Trento components and the
third-party system dependencies. Refer to its
xref:docs/README-deploy.adoc[Documentation]

Roles::

app::: Installs Trento Server components. Used in Deploymnet Playbook.
agent::: Installs Trento agent for information gathering. Used in Deployment Playbook.
postgres::: Installs PostgreSQL database server and configure it
with. Used in Deploymnet Playbook.  needed databases, users and
permissions. Used in Deploymnet Playbook.
rabbitmq::: Installs RabbitMQ message broker. Used in Deploymnet
Playbook.
prometheus::: Installs Prometheus metrics server. Used in Deploymnet
Playbook.
proxy::: Installs HTTP reverse proxy and configures it for
Trento-specific use-cases. Used in Deploymnet Playbook.
