---
- name: Deploy devbox
  ansible.builtin.import_playbook: deploy_devbox.yml

- name: Refresh inventory
  hosts: localhost
  connection: local
  tasks:
    - name: Refresh inventory
      ansible.builtin.meta: refresh_inventory

- name: Run Trento Ansible Playbook
  ansible.builtin.import_playbook: "{{ playbook_dir ~ '/../../../playbook.yml' }}"
  vars:
    ansible_ssh_private_key_file: "{{ hostvars.localhost.devbox_keypair_res.filename }}"
