# SPDX-FileCopyrightText: SUSE LLC
# SPDX-License-Identifier: Apache-2.0

---
web_docker_network_name: "{{ trento_docker_network_name }}"
web_force_pull_images: "{{ trento_force_pull_images }}"
web_container_image: ghcr.io/trento-project/trento-web:rolling
web_container_name: "{{ trento_web_container_name }}"
web_force_recreate_container: false
web_remove_container_image: true

# Overrides
web_prometheus_host: >-
  {{ (trento_prometheus_effective_host in ['localhost', '127.0.0.1', '::1']) | ternary('host.docker.internal', trento_prometheus_effective_host) }}
web_postgres_host: "host.docker.internal"
web_rabbitmq_host: "host.docker.internal"
