= Local Development Environment

You can test the playbook on a local virtual machine--called a
devbox--that you can quickly start and stop. This document explains
how to set up a devbox.

Currently, two types of VM management technologies are supported:

- Vagrant
- KubeVirt

Vagrant is considered deprecated.

== Prerequisites

Devboxes are configured to run Trento with a self-signed certificate
for `trento.local` domain. Make sure you add corresponding entry to
your `/etc/hosts` file and then accept the exception when prompted by
your browser. Your `/etc/hosts` should look similar to this:

----
...
127.0.0.1	localhost trento.local
...
----

You should be able to reach Trento using the following URL:
https://trento.local:<port>.

The `<port>` to access Trento on that domain should be setup by using
port-forwarding. Such configuration is specific to the VM-management
technology used. With some technologies this is configured to happen
automatically while with others the user needs to set this up
manually.

Please note that you should forward the port serving HTTPS/TLS
(eg. 443).

== Local development with KubeVirt

Refer to xref:local-development-kubevirt.adoc[Local Development
Environment with KubeVirt]

== Local development with Vagrant

Refer to xref:local-development-vagrant.adoc[Local Development
Environment with Vagrant]
