# SPDX-FileCopyrightText: SUSE LLC
# SPDX-License-Identifier: Apache-2.0

# code: language=ansible
---
- name: Cleanup Postgres installation
  become: true
  become_user: postgres
  vars:
    # Pipelining as workaround for when SSH connection is not made
    # with root and then switching to unprivileged user: There are
    # other possibilities:
    # https://docs.ansible.com/projects/ansible/latest/playbook_guide/playbooks_privilege_escalation.html#risks-of-becoming-an-unprivileged-user
    ansible_ssh_pipelining: true
  block:
    - name: Remove web database
      community.postgresql.postgresql_db:
        name: "{{ postgres_web_db }}"
        login_port: "{{ postgres_port }}"
        state: absent
        force: true

    - name: Remove web event store database
      community.postgresql.postgresql_db:
        name: "{{ postgres_web_event_store }}"
        login_port: "{{ postgres_port }}"
        state: absent
        force: true

    - name: Remove wanda event store database
      community.postgresql.postgresql_db:
        name: "{{ postgres_wanda_db }}"
        login_port: "{{ postgres_port }}"
        state: absent
        force: true

    - name: Remove web database user
      community.postgresql.postgresql_user:
        name: "{{ postgres_web_username }}"
        login_port: "{{ postgres_port }}"
        state: absent

    - name: Remove wanda database user
      community.postgresql.postgresql_user:
        name: "{{ postgres_wanda_username }}"
        login_port: "{{ postgres_port }}"
        state: absent

- name: Check postgres configuration backups
  become: true
  ansible.builtin.stat:
    path: "{{ item }}.trento-backup"
  loop:
    - /var/lib/pgsql/data/postgresql.conf
    - /var/lib/pgsql/data/pg_hba.conf
  register: __postgres_configuration_backups

- name: Restore postgres configuration
  become: true
  ansible.builtin.copy:
    src: "{{ item.item }}.trento-backup"
    dest: "{{ item.item }}"
    remote_src: true
    mode: preserve
  loop: "{{ __postgres_configuration_backups.results }}"
  when: item.stat.exists
  notify: Restart postgres

- name: Remove postgres configuration backups
  become: true
  ansible.builtin.file:
    path: "{{ item.item }}.trento-backup"
    state: absent
  loop: "{{ __postgres_configuration_backups.results }}"
  when: item.stat.exists
