# SPDX-FileCopyrightText: SUSE LLC
# SPDX-License-Identifier: Apache-2.0

# code: language=ansible
---
- name: Install Trento support tooling
  community.general.zypper:
    name:
      - "{{ supportutils_package_name }}"
      - "{{ supportutils_plugin_package_name }}"
    state: present
    update_cache: "{{ supportutils_update_cache }}"
  when:
    - supportutils_enabled | bool