# code: language=ansible
---
- name: Install Trento support tooling
  community.general.zypper:
    name: "{{ supportutils_packages }}"
    state: present
    update_cache: "{{ supportutils_update_cache }}"
  when:
    - ansible_distribution == "SLES_SAP"
    - ansible_distribution_version is version('15.5', '>=')
